routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::group(['prefix' => 'message', 'namespace' => 'Message'], function () {
        Route::resource('outbox', 'OutboxController');
        Route::resource('delivered', 'DeliveredController');
        Route::resource('inbox', 'InboxController');
        Route::get('check-inbox', 'InboxController@checkInbox')->name('inbox.check');
        Route::resource('broadcast', 'BroadCastController');
        Route::resource('schedule', 'ScheduleController');
        Route::get('check-schedule', 'ScheduleController@checkSchedule')->name('schedule.check');
        Route::resource('auto-reply', 'AutoReplyController');
    });
    Route::group(['namespace' => 'Pesanan'], function () {
        Route::resource('pesanan', 'PesananController');
        Route::get('pesanan-export', 'PesananController@export')->name('pesanan.export');
    });
    Route::group(['namespace' => 'Contact'], function () {
        Route::resource('contact', 'ContactController');
        Route::resource('group', 'GroupController');
    });
    Route::group(['namespace' => 'Bahan'], function () {
        Route::resource('bahan', 'BahanController');
    });
    Route::group(['namespace' => 'Jasa'], function () {
        Route::resource('jasa', 'JasaController');
    });
    Route::group(['namespace' => 'Profile'], function () {
        Route::resource('profile', 'ProfileController');
    });
});

resources/views/kontak/kontak/create.blade.php
@extends('layouts.sablon')
@section('content')
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
<div class="row">
    <div class="col-6">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">
                {{ isset($title) ? $title : '' }}
                </div>
            </div>
            <div class="ibox-body">
            @include('partials._info')
                <form id="form_tulis_pesan" action="{{ route('contact.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="">Nama Pelanggan</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="Name" value="{{ old('Name') }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">Grup</label>
                        <div class="input-group-icon left">
                            <select id="kontak" class="js-example-basic-single form-control" name="GroupID">
                                <option value="0">-- Pilih Grup --</option>
                                @foreach($group as $k)
                                <option {{ old('id_group') == $k->GroupID ? 'selected' : '' }} value="{{$k->GroupID}}">{{$k->NameGroup}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">Nomor HP</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="Number" value="{{ old('Number') }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-danger" onclick="window.history.go(-1)" type="button"><i class="fa fa-arrow-left"></i>
                            Batal</button>
                            <button class="btn btn-primary" type="submit"><i class="fa fa-floppy-o"></i> Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $('.js-example-basic-single').select2();
});
</script>
@endsection

resources/views/kontak/kontak/edit.blade.php
@extends('layouts.sablon')
@section('content')
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
<div class="row">
    <div class="col-6">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">
                {{ isset($title) ? $title : '' }}
                </div>
            </div>
            <div class="ibox-body">
            @include('partials._info')
                <form id="form_tulis_pesan" action="{{ route('contact.update', $data->ID) }}" method="post">
                    @csrf
                    @method('PATCH')
                    <div class="form-group">
                        <label for="">Nama Pelanggan</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="Name" value="{{ $data->Name }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">Grup</label>
                        <div class="input-group-icon left">
                            <select id="kontak" class="js-example-basic-single form-control" name="GroupID">
                                <option value="0">-- Pilih Grup --</option>
                                @foreach($group as $k)
                                <option {{ $data->GroupID == $k->GroupID ? 'selected' : '' }} value="{{$k->GroupID}}">{{$k->NameGroup}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">Nomor HP</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="Number" value="{{ $data->Number }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-danger" onclick="window.history.go(-1)" type="button"><i class="fa fa-arrow-left"></i>
                            Batal</button>
                            <button class="btn btn-primary" type="submit"><i class="fa fa-floppy-o"></i> Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $('.js-example-basic-single').select2();
});
</script>
@endsection

resources/views/kontak/kontak/index.blade.php
@extends('layouts.sablon')
@section('content')
<div class="ibox">
    <div class="ibox-head">
        <div class="ibox-title">
            {{ $title }}
        </div>
    </div>

    <div class="ibox-body">
        @include('partials._info')
        <table class="table table-striped table-bordered table-hover" id="table" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th width="10">No</th>
                    <th width="150">Nama Pelanggan</th>
                    <th>Nomor HP</th>
                    <th width="100">Grup</th>
                    <th width="80">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $d)
                <tr>
                    <td>{{ $loop->iteration}}</td>
                    <td>{{ $d->Name }}</td>
                    <td>{{ $d->Number }}</td>
                    <td>{{ $d->group ? $d->group->NameGroup : 'Belum ada' }}</td>
                    <td align="center">
                        <form id="f_{{$d->ID}}" action="{{route('contact.destroy',$d->ID)}}" method="post" style="display:inline">
                        @method('DELETE')
                        @csrf
                        <button onclick="return confirm('Yakin Ingin Hapus Kontak Ini?')"  class="btn  btn-danger" type="submit" value="Delete"><i class="fa fa-trash-o"></i></button>
                        </form>
                        <a href="{{ route('contact.edit', $d->ID) }}" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
<script>
$(document).ready(function(){
        $("#table_length").append('<a  href="{{ route('contact.create') }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
    });
</script>
@endsection