routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::group(['prefix' => 'message', 'namespace' => 'Message'], function () {
        Route::resource('outbox', 'OutboxController');
        Route::resource('delivered', 'DeliveredController');
        Route::resource('inbox', 'InboxController');
        Route::get('check-inbox', 'InboxController@checkInbox')->name('inbox.check');
        Route::resource('broadcast', 'BroadCastController');
        Route::resource('schedule', 'ScheduleController');
        Route::get('check-schedule', 'ScheduleController@checkSchedule')->name('schedule.check');
        Route::resource('auto-reply', 'AutoReplyController');
    });
    Route::group(['namespace' => 'Pesanan'], function () {
        Route::resource('pesanan', 'PesananController');
        Route::get('pesanan-export', 'PesananController@export')->name('pesanan.export');
    });
    Route::group(['namespace' => 'Contact'], function () {
        Route::resource('contact', 'ContactController');
        Route::resource('group', 'GroupController');
    });
    Route::group(['namespace' => 'Bahan'], function () {
        Route::resource('bahan', 'BahanController');
    });
    Route::group(['namespace' => 'Jasa'], function () {
        Route::resource('jasa', 'JasaController');
    });
    Route::group(['namespace' => 'Profile'], function () {
        Route::resource('profile', 'ProfileController');
    });
});

resources/views/pesan/kotak_masuk/index.blade.php
@extends('layouts.sablon')
@section('content')
<div class="ibox">
    <div class="ibox-head">
        <div class="ibox-title">
            {{ $title }}
        </div>
    </div>

    <div class="ibox-body">
        @include('partials._info')
        <table class="table table-striped table-bordered table-hover" id="table" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th width="10">No</th>
                    <th width="150">Pengirim</th>
                    <th width="300">Pesan</th>
                    <th width="100">Tanggal</th>
                    <th width="50">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $d)
                <tr style="{{ $d->Processed == 'false' ? 'background-color : #A3DAEC' : '' }}">
                    <td>{{ $loop->iteration}}</td>
                    <td>{{ $d->user ? $d->user->Name : 'Belum terdaftar' }}
                        <div>{{ $d->SenderNumber }}</div>
                    </td>
                    <td class="message clickable-row" data-href="{{ route('inbox.edit', $d->ID) }}" style="cursor : pointer">
                        <span class="wrap-text">{{ $d->TextDecoded }}</span>
                    </td>
                    <td>{{ date('j M Y H:i', strtotime($d->ReceivingDateTime)) }}</td>
                    <td align="center">
                        <form id="f_{{$d->ID}}" action="{{route('inbox.destroy',$d->ID)}}" method="post" style="display:inline">
                        @method('DELETE')
                        @csrf
                        <button onclick="return confirm('Yakin Ingin Hapus Pesan Ini?')"  class="btn  btn-danger" type="submit" value="Delete"><i class="fa fa-trash-o"></i></button>
                        </form>
                        <a href="{{ route('inbox.edit', $d->ID) }}" class="btn btn-primary"><i class="fa fa-reply"></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
<script>
jQuery(document).ready(function($) {
    $(".clickable-row").click(function() {
        window.location = $(this).data("href");
    });
});
</script>
@endsection

resources/views/pesan/kotak_masuk/reply.blade.php
@extends('layouts.sablon')
@section('content')
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
<div class="row">
    <div class="col-6">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">
                {{ isset($title) ? $title : '' }}
                </div>
            </div>
            <div class="ibox-body">
            @include('partials._info')
                <form id="form_tulis_pesan" action="{{ route('inbox.update',$id) }}" method="post">
                    @csrf
                    @method('patch')
                    <div class="form-group">
                        <label for="">Kontak</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="kontak" value="{{ $data->SenderNumber  }}" readOnly>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">Pesan</label>
                        <div class="input-group-icon left">
                            <textarea id="" cols="100" rows="5" readOnly>{{ $data->TextDecoded }}</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">Balas</label>
                        <div class="input-group-icon left">
                            <textarea name="pesan" id="" cols="100" rows="5"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-danger" onclick="window.history.go(-1)" type="button"><i class="fa fa-arrow-left"></i>
                            Batal</button>
                        <button class="btn btn-primary" type="submit"><i class="fa fa-paper-plane-o"></i> Balas</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $('.js-example-basic-single').select2();
});
</script>
@endsection