routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::group(['prefix' => 'message', 'namespace' => 'Message'], function () {
        Route::resource('outbox', 'OutboxController');
        Route::resource('delivered', 'DeliveredController');
        Route::resource('inbox', 'InboxController');
        Route::get('check-inbox', 'InboxController@checkInbox')->name('inbox.check');
        Route::resource('broadcast', 'BroadCastController');
        Route::resource('schedule', 'ScheduleController');
        Route::get('check-schedule', 'ScheduleController@checkSchedule')->name('schedule.check');
        Route::resource('auto-reply', 'AutoReplyController');
    });
    Route::group(['namespace' => 'Pesanan'], function () {
        Route::resource('pesanan', 'PesananController');
        Route::get('pesanan-export', 'PesananController@export')->name('pesanan.export');
    });
    Route::group(['namespace' => 'Contact'], function () {
        Route::resource('contact', 'ContactController');
        Route::resource('group', 'GroupController');
    });
    Route::group(['namespace' => 'Bahan'], function () {
        Route::resource('bahan', 'BahanController');
    });
    Route::group(['namespace' => 'Jasa'], function () {
        Route::resource('jasa', 'JasaController');
    });
    Route::group(['namespace' => 'Profile'], function () {
        Route::resource('profile', 'ProfileController');
    });
});

resources/views/kontak/grup/create.blade.php
@extends('layouts.sablon')
@section('content')
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
<div class="row">
    <div class="col-6">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">
                {{ isset($title) ? $title : '' }}
                </div>
            </div>
            <div class="ibox-body">
            @include('partials._info')
                <form id="form_tulis_pesan" action="{{ route('group.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="">Nama Grup</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="NameGroup" value="{{ old('NameGroup') }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-danger" onclick="window.history.go(-1)" type="button"><i class="fa fa-arrow-left"></i>
                            Batal</button>
                            <button class="btn btn-primary" type="submit"><i class="fa fa-floppy-o"></i> Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $('.js-example-basic-single').select2();
});
</script>
@endsection

resources/views/kontak/grup/edit.blade.php
@extends('layouts.sablon')
@section('content')
<div class="row">
    <div class="col-6">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">
                {{ isset($title) ? $title : '' }}
                </div>
            </div>
            <div class="ibox-body">
            @include('partials._info')
                <form id="form_tulis_pesan" action="{{ route('group.update', $data->GroupID) }}" method="post">
                    @csrf
                    @method('PATCH')
                    <div class="form-group">
                        <label for="">Nama Grup</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="NameGroup" value="{{ $data->NameGroup }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-danger" onclick="window.history.go(-1)" type="button"><i class="fa fa-arrow-left"></i>
                            Batal</button>
                            <button class="btn btn-primary" type="submit"><i class="fa fa-floppy-o"></i> Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $('.js-example-basic-single').select2();
});
</script>
@endsection

resources/views/kontak/grup/index.blade.php
@extends('layouts.sablon')
@section('content')
<div class="ibox">
    <div class="ibox-head">
        <div class="ibox-title">
            {{ $title }}
        </div>
    </div>

    <div class="ibox-body">
        @include('partials._info')
        <table class="table table-striped table-bordered table-hover" id="table" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th width="10">No</th>
                    <th width="150">Nama Grup</th>
                    <th width="80">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $d)
                <tr>
                    <td>{{ $loop->iteration}}</td>
                    <td>{{ $d->NameGroup }}</td>
                    <td align="center">
                        <form id="f_{{$d->GroupID}}" action="{{route('group.destroy',$d->GroupID)}}" method="post" style="display:inline">
                        @method('DELETE')
                        @csrf
                        <button onclick="return confirm('Yakin Ingin Hapus Group Ini?')"  class="btn  btn-danger" type="submit" value="Delete"><i class="fa fa-trash-o"></i></button>
                        </form>
                        <a href="{{ route('group.edit', $d->GroupID) }}" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
<script>
$(document).ready(function(){
        $("#table_length").append('<a  href="{{ route('group.create') }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
    });
</script>
@endsection