routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::group(['prefix' => 'message', 'namespace' => 'Message'], function () {
        Route::resource('outbox', 'OutboxController');
        Route::resource('delivered', 'DeliveredController');
        Route::resource('inbox', 'InboxController');
        Route::get('check-inbox', 'InboxController@checkInbox')->name('inbox.check');
        Route::resource('broadcast', 'BroadCastController');
        Route::resource('schedule', 'ScheduleController');
        Route::get('check-schedule', 'ScheduleController@checkSchedule')->name('schedule.check');
        Route::resource('auto-reply', 'AutoReplyController');
    });
    Route::group(['namespace' => 'Pesanan'], function () {
        Route::resource('pesanan', 'PesananController');
        Route::get('pesanan-export', 'PesananController@export')->name('pesanan.export');
    });
    Route::group(['namespace' => 'Contact'], function () {
        Route::resource('contact', 'ContactController');
        Route::resource('group', 'GroupController');
    });
    Route::group(['namespace' => 'Bahan'], function () {
        Route::resource('bahan', 'BahanController');
    });
    Route::group(['namespace' => 'Jasa'], function () {
        Route::resource('jasa', 'JasaController');
    });
    Route::group(['namespace' => 'Profile'], function () {
        Route::resource('profile', 'ProfileController');
    });
});

app/Models/Bahan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Bahan extends Model
{
    protected $fillable = [
        'nama', 'harga'
    ];
    protected $table = 'tbl_bahan';
    public $timestamps = false;
}

app/Http/Controllers/Bahan/BahanController.php
<?php

namespace App\Http\Controllers\Bahan;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Bahan;

class BahanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $title = "Data Bahan";
        $data = Bahan::get();
        return view('bahan.index', compact('data', 'title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $title = "Tambah Bahan";
        return view('bahan.create', compact('title'));
    }
    public function edit($id)
    {
        $title = "Edit Bahan";
        $data =Bahan::find($id);
        return view('bahan.edit', compact('data', 'title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $Bahan = Bahan::create($request->all());
        return redirect()->route('bahan.index')->with(['success' => 'Berhasil Menambah Bahan']);
    }
    public function update(Request $request, $id)
    {
        $Bahan = Bahan::where('ID', $id)->update($request->except('_token', '_method'));
        return redirect()->route('bahan.index')->with(['success' => 'Berhasil Mengubah Bahan']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Bahan::find($id)->delete();
        return redirect()->back()->with(['danger' => 'Berhasil Menghapus Bahan Pelanggan']);
    }
}

resources/views/bahan/create.blade.php
@extends('layouts.sablon')
@section('content')
<link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
<div class="row">
    <div class="col-6">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">
                {{ isset($title) ? $title : '' }}
                </div>
            </div>
            <div class="ibox-body">
            @include('partials._info')
                <form id="form_tulis_pesan" action="{{ route('bahan.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="">Nama Bahan</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="nama" value="{{ old('NameGroup') }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">Harga Bahan</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="harga" value="{{ old('NameGroup') }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-danger" onclick="window.history.go(-1)" type="button"><i class="fa fa-arrow-left"></i>
                            Batal</button>
                            <button class="btn btn-primary" type="submit"><i class="fa fa-floppy-o"></i> Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $('.js-example-basic-single').select2();
});
</script>
@endsection

resources/views/bahan/edit.blade.php
@extends('layouts.sablon')
@section('content')
<div class="row">
    <div class="col-6">
        <div class="ibox">
            <div class="ibox-head">
                <div class="ibox-title">
                {{ isset($title) ? $title : '' }}
                </div>
            </div>
            <div class="ibox-body">
            @include('partials._info')
                <form id="form_tulis_pesan" action="{{ route('bahan.update', $data->id) }}" method="post">
                    @csrf
                    @method('PATCH')
                    <div class="form-group">
                        <label for="">Nama Bahan</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="nama" value="{{ $data->nama }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="">Harga Bahan</label>
                        <div class="input-group">
                            <input type="text" class="form-control" name="harga" value="{{ $data->harga }}">
                        </div>
                    </div>
                    <div class="form-group">
                        <button class="btn btn-danger" onclick="window.history.go(-1)" type="button"><i class="fa fa-arrow-left"></i>
                            Batal</button>
                            <button class="btn btn-primary" type="submit"><i class="fa fa-floppy-o"></i> Simpan</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
$(document).ready(function() {
    $('.js-example-basic-single').select2();
});
</script>
@endsection

resources/views/bahan/index.blade.php
@extends('layouts.sablon')
@section('content')
<div class="ibox">
    <div class="ibox-head">
        <div class="ibox-title">
            {{ $title }}
        </div>
    </div>

    <div class="ibox-body">
        @include('partials._info')
        <table class="table table-striped table-bordered table-hover" id="table" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th width="10">No</th>
                    <th width="150">Nama Bahan</th>
                    <th width="150">Harga Bahan</th>
                    <th width="80">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($data as $d)
                <tr>
                    <td>{{ $loop->iteration}}</td>
                    <td>{{ $d->nama }}</td>
                    <td>{{ $d->harga }}</td>
                    <td align="center">
                        <form id="f_{{$d->id}}" action="{{route('bahan.destroy',$d->id)}}" method="post" style="display:inline">
                        @method('DELETE')
                        @csrf
                        <button onclick="return confirm('Yakin Ingin Hapus Bahan Ini?')"  class="btn  btn-danger" type="submit" value="Delete"><i class="fa fa-trash-o"></i></button>
                        </form>
                        <a href="{{ route('bahan.edit', $d->id) }}" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
<script>
$(document).ready(function(){
        $("#table_length").append('<a  href="{{ route('bahan.create') }}"> <button type="button" class="btn btn-outline-primary ml-3">Tambah</button></a>');
    });
</script>
@endsection